FROM rust:slim-bullseye

# Update default packages
RUN apt-get update && apt-get install --no-install-recommends -y \
    build-essential \
    curl \
    cabextract \
    aria2 \
    #wimtools \
    #chntpw \
    #genisoimage \
    p7zip-full \
    libssl-dev \
    pkg-config \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*


# Get Rust
#RUN curl https://sh.rustup.rs -sSf | bash -s -- -y

#ENV PATH="/root/.cargo/bin:${PATH}"

#RUN apt install 
RUN cargo install pdblister
#RUN echo 'source $HOME/.cargo/env' >> $HOME/.bashrc ; PATH="/root/.cargo/bin:${PATH}" ; cargo install pdblister -y


