FROM rust:slim-bullseye

# Update default packages
RUN apt-get update && apt-get install --no-install-recommends -y \
    build-essential \
    curl \
    cabextract \
    aria2 \
    p7zip-full \
    libssl-dev \
    pkg-config \
    python3-dev \
    wimtools \
    file \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*

RUN apt-get update && apt-get install -y python3-pip
RUN python3 -m pip install --no-cache-dir tqdm pefile
#RUN cargo install --git https://github.com/ErezAmihud/pdblister


