name: Build Docker

on:
  push:
    branches: main
    paths: code/dockerfile

jobs:
  build-and-publish-head:
    runs-on: ubuntu-latest
    permissions:
      packages: write
    steps:
        - uses: actions/checkout@v4

        - name: Log in to the Container registry
          uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
          with:
            registry: https://ghcr.io
            username: ${{ github.actor }}
            password: ${{ secrets.GITHUB_TOKEN }}

        - name: Build and push Docker image
          uses: docker/build-push-action@ad44023a93711e3deb337508980b4b5e9bcdc5dc
          with:
            context: code/
            push: true
            tags: ghcr.io/erezamihud/pdblist:latest
