name: Nicer Download uup entries
on:
  push:
    branches:
      - "feature/actual-data"

jobs:
  build:
    name: Run
    env:
      editions: core;professional
      uuid: 64ad5ee4-fa4e-4106-a2e5-c9f1c3eb6e4a
      destDir: UUPs
      manifestdir: manifest_dir
      tempScript: aria2_script.txt
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.split_file.outputs.matrix }}
    container:
      image: ghcr.io/erezamihud/pdblist:latest
    steps:
      - name: Checkout main
        uses: actions/checkout@v4
      - name: Get download lines
        run: curl "https://uupdump.net/get.php?id=$uuid&pack=en-us&edition=$editions&aria2=2" -o"$tempScript"
      - id: split_file
        name: Split file
        run: python3 -c "import json;print(json.dumps({'download_url': open('$tempScript','r').read().split('\n\n')}))"
      #- name: Run main
      #  run: chmod +x ./code/main.sh && bash ./code/main.sh
  
      #- name: Archive manifest result
      #  uses: actions/upload-artifact@v4
      #  with:
      #    name: manifest.out
      #    path: manifest.out
  job2:
    needs: build
    runs-on: ubuntu-latest
    strategy:
      matrix: ${{fromJson(needs.build.outputs.matrix)}}
    steps:
    - run: echo ${{ matrix.download_url }} > a.txt
    - run: 
    - run: echo ${{ matrix.project }}
    - run: echo ${{ matrix.config }}