name: Detect more uup entries
on:
  workflow_dispatch:
  schedule:
   - cron: '0 */4 * * *'

permissions:
  contents: write

concurrency:
  group: main-yml
  cancel-in-progress: false

jobs:
  list_releases:
    name: Get not figured out builds
    runs-on: ubuntu-latest
    outputs:
      uuids: ${{ steps.pick_builds.outputs.uuid_matrix }}
    steps:
      - uses: actions/checkout@v7
      - run: pip install -r requirements.txt
      - run: python ./code/daily.py ${{ vars.ALLOWED_DOWNLOAD_SIZE }}
        id: pick_builds

  download_releases:
    needs: list_releases
    if: ${{ needs.list_releases.outputs.uuids != '[]' }}
    strategy:
      fail-fast: false
      matrix:
        uuid: ${{ fromJson(needs.list_releases.outputs.uuids) }}
    uses: ./.github/workflows/download_build.yml
    with:
      uuid: ${{matrix.uuid}}

  publish_docs:
    needs: download_releases
    name: Deploy docs
    runs-on: ubuntu-latest
    if: ${{ always() }}
    concurrency: publish_docs
    steps:
      - name: Checkout main
        uses: actions/checkout@v7
      - run: pip install -r requirements.txt
      - run: git config user.name 'github-actions[bot]' && git config user.email 'github-actions[bot]@users.noreply.github.com'
      - name: Publish docs
        run: mkdocs gh-deploy --force
