name: Detect more uup entries
on:
  push:
    branches:
      - "feature/actual-data"

jobs:
  build:
    name: Run
    env:
      editions: core;professional
      uuid: 64ad5ee4-fa4e-4106-a2e5-c9f1c3eb6e4a
      destDir: UUPs
      manifestdir: manifest_dir
      tempScript: aria2_scripttxt
    runs-on: ubuntu-latest
    permissions: 
      packages: read
    container:
      image: ghcr.io/erezamihud/pdblist:latest
    steps:
      - name: Checkout main
        uses: actions/checkout@v4
      - run: mkdir $destDir ; mkdir $manifestdir
      - name: Get download lines
        run: aria2c --no-conf --console-log-level=warn --log-level=info --log="aria2_download.log" -o"$tempScript" --allow-overwrite=true --auto-file-renaming=false "https://uupdump.net/get.php?id=$uuid&pack=en-us&edition=$editions&aria2=2"
      - name: Split file
        run: python3 -c "import json;print(json.dumps(open('$tempScript','r').read().split('\n\n')))"
      #- name: Run main
      #  run: chmod +x ./code/main.sh && bash ./code/main.sh
  
      #- name: Archive manifest result
      #  uses: actions/upload-artifact@v4
      #  with:
      #    name: manifest.out
      #    path: manifest.out