name: Publish docs via GitHub Pages
on:
  push:
    branches:
      - main
    paths:
      - "builds_state.json"
      - "mkdocs.yml"
      - "code/gen_docs_index.py"

permissions:
  contents: write

jobs:
  build:
    name: Deploy docs
    runs-on: ubuntu-latest
    concurrency: publish_docs
    steps:
      - name: Checkout main
        uses: actions/checkout@v7
      - run: pip install -r requirements.txt
      - run: git config user.name 'github-actions[bot]' && git config user.email 'github-actions[bot]@users.noreply.github.com'
      - name: Publish docs
        run: mkdocs gh-deploy --force
