name: Tests
on:
  push:
  pull_request:

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Installations
        run: sudo apt-get update && sudo apt-get install --no-install-recommends -y wimtools && pip install -r requirements.txt pytest
      - run: pip install -e ./cli
      - run: pytest tests/
      - name: Docs build
        run: mkdocs build --strict
