name: test
on:
  push:
    branches:
      - "feature/actual-data"



jobs:
  main:
    concurrency:
      group: hello
    name: Get not figured out builds
    runs-on: ubuntu-latest
    strategy:
      matrix:
        name:
          - 1
          - 2
          - 3
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{github.ref_name}}
      - run: echo ${{matrix.name}} >> test.txt
        id: version_list_step
      - uses: EndBug/add-and-commit@v9
        with:
          add: test.txt
          message: 'Automated commit, test'